const bgByType = {
  normal: "bg-gradient-to-t from-gray-200 to-gray-500",
  fighting: "bg-gradient-to-t from-red-200 to-red-700",
  flying: "bg-gradient-to-t from-purple-200 to-purple-400",
  poison: "bg-gradient-to-t from-pink-200 to-pink-700",
  ground: "bg-gradient-to-t from-yellow-200 to-yellow-500",
  rock: "bg-gradient-to-t from-yellow-200 to-yellow-600",
  bug: "bg-gradient-to-t from-yellow-200 to-yellow-300",
  ghost: "bg-gradient-to-t from-purple-200 to-purple-800",
  steel: "bg-gradient-to-t from-gray-200 to-gray-400",
  fire: "bg-gradient-to-t from-orange-200 to-orange-500",
  water: "bg-gradient-to-t from-indigo-200 to-indigo-500",
  grass: "bg-gradient-to-t from-green-200 to-green-500",
  electric: "bg-gradient-to-t from-yellow-200 to-yellow-400",
  psychic: "bg-gradient-to-t from-pink-200 to-pink-500",
  ice: "bg-gradient-to-t from-teal-200 to-teal-300",
  dragon: "bg-gradient-to-t from-purple-200 to-purple-600",
  dark: "bg-gradient-to-t from-gray-200 to-gray-700",
  fairy: "bg-gradient-to-t from-pink-200 to-pink-400",
  unknown: "bg-gradient-to-t from-brown-200 to-brown-400",
  shadow: "bg-gradient-to-t from-gray-200 to-gray-800",
};

const borderByType = {
  normal: "border-gray-500",
  fighting: "border-red-700",
  flying: "border-purple-400",
  poison: "border-pink-700",
  ground: "border-yellow-500",
  rock: "border-yellow-600",
  bug: "border-yellow-300",
  ghost: "border-purple-800",
  steel: "border-gray-400",
  fire: "border-orange-500",
  water: "border-indigo-500",
  grass: "border-green-500",
  electric: "border-yellow-400",
  psychic: "border-pink-500",
  ice: "border-teal-300",
  dragon: "border-purple-600",
  dark: "border-gray-700",
  fairy: "border-pink-400",
  unknown: "border-brown-400",
  shadow: "border-gray-800",
};

const colorByType = {
  normal: "text-gray-500",
  fighting: "text-red-700",
  flying: "text-purple-400",
  poison: "text-pink-700",
  ground: "text-yellow-500",
  rock: "text-yellow-600",
  bug: "text-yellow-300",
  ghost: "text-purple-800",
  steel: "text-gray-400",
  fire: "text-orange-500",
  water: "text-indigo-500",
  grass: "text-green-500",
  electric: "text-yellow-400",
  psychic: "text-pink-500",
  ice: "text-teal-300",
  dragon: "text-purple-600",
  dark: "text-gray-700",
  fairy: "text-pink-400",
  unknown: "text-brown-400",
  shadow: "text-gray-800",
};

const boxByType = {
  normal: "bg-gray-500 text-white p-2 m-2 rounded-sm ",
  fighting: "bg-red-700 text-white p-2 m-2 rounded-sm ",
  flying: "bg-purple-400 text-white p-2 m-2 rounded-sm ",
  poison: "bg-pink-700 text-white p-2 m-2 rounded-sm ",
  ground: "bg-yellow-500 text-white p-2 m-2 rounded-sm ",
  rock: "bg-yellow-600 text-white p-2 m-2 rounded-sm ",
  bug: "bg-yellow-300 text-white p-2 m-2 rounded-sm ",
  ghost: "bg-purple-800 text-white p-2 m-2 rounded-sm ",
  steel: "bg-gray-400 text-white p-2 m-2 rounded-sm ",
  fire: "bg-orange-500 text-white p-2 m-2 rounded-sm ",
  water: "bg-indigo-500 text-white p-2 m-2 rounded-sm ",
  grass: "bg-green-500 text-white p-2 m-2 rounded-sm ",
  electric: "bg-yellow-400 text-white p-2 m-2 rounded-sm ",
  psychic: "bg-pink-500 text-white p-2 m-2 rounded-sm ",
  ice: "bg-teal-300 text-white p-2 m-2 rounded-sm ",
  dragon: "bg-purple-600 text-white p-2 m-2 rounded-sm ",
  dark: "bg-gray-700 text-white p-2 m-2 rounded-sm ",
  fairy: "bg-pink-400 text-white p-2 m-2 rounded-sm ",
  unknown: "bg-brown-400 text-white p-2 m-2 rounded-sm ",
  shadow: "bg-gray-800 text-white p-2 m-2 rounded-sm ",
};

export { bgByType, borderByType, colorByType, boxByType };
